In [10]:
a <- matrix(1:4, 2, 2, TRUE)
b <- matrix(c(3, 6, 2, 7, 1, 4, 5, 9, 8), 3, 3, TRUE)
print(a)
print(b)

     [,1] [,2]
[1,]    1    2
[2,]    3    4
     [,1] [,2] [,3]
[1,]    3    6    2
[2,]    7    1    4
[3,]    5    9    8


In [11]:
t(a)
det(a)
solve(a)
t(b)
det(b)
solve(b)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

[1] -2

[,1] [,2]
[1,] -2.0  1.0
[2,]  1.5 -0.5

[,1] [,2] [,3]
[1,] 3    7    5   
[2,] 6    1    9   
[3,] 2    4    8

[1] -184

[,1]       [,2]        [,3]       
[1,]  0.1521739  0.16304348 -0.11956522
[2,]  0.1956522 -0.07608696 -0.01086957
[3,] -0.3152174 -0.01630435  0.21195652