In [1]:
#1.1 f(x) = x^3 + x^2 - 6
#1.2 g(a, b) = ab(b - a)
#1.3 h(m, n) = (√m/n) + m - 2n

#2.1 f(a, b) = (a + b)ab
#2.2 h(m, n) = |m|n − mn
#2.3 g(x) = x'x − 2x

In [12]:
#1.1
f1 <- function(x){
    h <- x^3 + x^2 - 6
    return (h)
}
#1.2
f2 <- function(a, b){
    h <- a*b*(b-a)
    return (h)
}
#1.3
f3 <- function(m, n){
    h <- (sqrt(m)/n) + m - 2*n
    return (h)
}

In [13]:
f1(6)
f2(8, 1)
f3(16, 6)

[1] 246

[1] -56

[1] 4.666667

In [19]:
#2.1
f4 <- function(a, b){
    h <- (a + b) %*% a %*% b
    return (h)
}
#2.2
f5 <- function(m, n){
    h <- det(m)*n - m %*% n
    return (h)
}
#2.3
f6 <- function(x){
    h <- solve(x) %*% x - 2*x
    return (h)
}

In [20]:
values1 <- sample(1:20, 4)
values2 <- sample(1:20, 4)

a <- matrix(values1, 2, 2)
b <- matrix(values2, 2, 2)

f4(a, b)
f5(a, b)
f6(a)

[,1]  [,2] 
[1,]  8158 15072
[2,] 11874 22004

[,1] [,2]
[1,] 572  1288
[2,] 494   608

[,1] [,2]
[1,] -13   -4 
[2,] -32  -29