In [2]:
#Creata a Matrix
a <- matrix(c(1, 2, 3, 4, 5, 6, 7, 8, 9), 3, 3, TRUE)
print(a)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


In [4]:
#Accessing Elements of Matrix
a[1, 2]
a[1, ]
a[ , 1]
a[1:2, ]
a[ , 1:2]
diag(a)

[1] 2

[1] 1 2 3

[1] 1 4 7

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

[,1] [,2]
[1,] 1    2   
[2,] 4    5   
[3,] 7    8

[1] 1 5 9

In [35]:
a[-1]
a[-1, ]
a[-2]
a[-3]

[1] 4 7 2 5 8 3 6 9

[,1] [,2] [,3]
[1,] 4    5    6   
[2,] 7    8    9

[1] 1 7 2 5 8 3 6 9

[1] 1 4 2 5 8 3 6 9

In [6]:
print(a)
which(a[ , 1] > 2)
which(a[2, ] < 5)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


[1] 2 3

[1] 1