In [4]:
a <- matrix(c(1, 2, 3, 9, 5, 6, 7, 8, 9), 3, 3, TRUE)
b <- matrix(c(3, 6, 2, 7, 1, 4, 5, 9, 8), 3, 3, TRUE)
print(a)
print(b)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    9    5    6
[3,]    7    8    9
     [,1] [,2] [,3]
[1,]    3    6    2
[2,]    7    1    4
[3,]    5    9    8


[1] 30

[,1]      [,2] [,3]      
[1,] -0.100000  0.2 -0.1000000
[2,] -1.300000 -0.4  0.7000000
[3,]  1.233333  0.2 -0.4333333

In [11]:
a + b

[,1] [,2] [,3]
[1,]  4    8    5  
[2,] 11    6   10  
[3,] 12   17   17

In [12]:
b - a

[,1] [,2] [,3]
[1,]  2    4   -1  
[2,]  3   -4   -2  
[3,] -2    1   -1

In [33]:
2 * a

[,1] [,2] [,3]
[1,]  2    4    6  
[2,]  8   10   12  
[3,] 14   16   18

In [35]:
e <- a / 3
d <- a %*% b
f <- a[-1, ] %*% b[ , -1]
print(e)
print(d)
print(f)

          [,1]      [,2] [,3]
[1,] 0.3333333 0.6666667    1
[2,] 1.3333333 1.6666667    2
[3,] 2.3333333 2.6666667    3
     [,1] [,2] [,3]
[1,]   32   35   34
[2,]   77   83   76
[3,]  122  131  118
     [,1] [,2]
[1,]   83   76
[2,]  131  118


In [45]:
print(a)
print(b)
g <- cbind(a[ , 1], b[ , 2])
h <- rbind(a[1, ], b[2, ])
print(g)
print(h)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
     [,1] [,2] [,3]
[1,]    3    6    2
[2,]    7    1    4
[3,]    5    9    8
     [,1] [,2]
[1,]    1    6
[2,]    4    1
[3,]    7    9
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    7    1    4
