In [8]:
#2
A <- matrix(c(1, 2, 3, 8, 2, 9), 3, 2, TRUE)
B <- matrix(c(5, 4, 8, 2), 2, 2, TRUE)

In [10]:
#2.a
A %*% B

#2.b
x <- A %*% solve(B)
x

#2.c
y <- A %*% t(B)
y

#2.d
3 * (x + y)

[,1] [,2]
[1,] 21    8  
[2,] 79   28  
[3,] 82   26

[,1]      [,2]     
[1,]  40.90909  35.18182
[2,] 148.90909 116.18182
[3,] 147.27273  96.95455

In [73]:
#1
A <- matrix(c(1, 1, 3, 5, 2, 6, -2, -1, -3), 3, 3, TRUE)

In [74]:
#1.a
A %*% A %*% A

#1.b
y <- cbind(A[ , 2]) + cbind(A[ , 3])
A[ , 3] <- y
A

[,1] [,2] [,3]
[1,] 0    0    0   
[2,] 0    0    0   
[3,] 0    0    0

[,1] [,2] [,3]
[1,]  1    1    4  
[2,]  5    2    8  
[3,] -2   -1   -4

In [37]:
#4
A <- matrix(1:9, 3, 3, TRUE)

In [58]:
for (j in 1:ncol(A)){
    A[1, j] <- A[j, 1] * 0
    if (A[2, 1] && A[3, 1] != 1){
        A[2, 1] <- A[2, 1] / A[2, 1]
        A[3, 1] <- A[3, 1] / A[3, 1]
    }
}
A

[,1] [,2] [,3]
[1,] 0     0    0  
[2,] 1     2    8  
[3,] 1    -1   -4

In [20]:
#3
A <- matrix(c(1, 2, -3, -2, 1, 2, 3, 1, -2), 3, 3)
b <- c(7, 4, -10)

In [36]:
#3.a
showEqn(A, b)
#3.b
Solve(A, b)
solve(A) %*% b
inv(A) %*% b
#3.c
plotEqn3d(A, b, xlim=c(0, 4), ylim=c(0, 4))
#3.d
echelon(A, b)
echelon(A, b, verbose=TRUE, fractions=TRUE)

ERROR: Error in showEqn(A, b): could not find function "showEqn"
